### ISSUE TITLE
Best practices for loading multiple solr cores

### ISSUE THREAD

**Issue by cassieramen** [10gen-labs/mongo-connector#186]
Any advice on how to load multiple solr cores from different collections?

**Comment by evalapply** [comment]
Hello, I'm a little confused. It seems it's possible to pass more than one url in ```--target-url[s]``` and more than one docmanager in ```--docManager/doc-managers``` (and it was like that in November 2014 already). Is it really the case that multiple instances are neccessary? At least the justification in the second comment is not clear.

**Comment by lovett89** [comment]
@evalapply 
You're right- it's possible to target more than one core with a single instance, but it's not possible to divide input collections from MongoDB among the cores; all collections go to all cores. If this isn't what you want, then one solution is to run multiple instances of the connector so that you can refine what collections go into each core. I hope that clarifies things.

**Comment by evalapply** [comment]
Yes, it's clear now :) Thank you very much.

**Comment by lovett89** [comment]
Closing this. This question is now part of the [FAQ](https://github.com/10gen-labs/mongo-connector/wiki/FAQ)
