### ISSUE TITLE
Updating the mapping in elasticsearch

### ISSUE THREAD

**Issue by BlackRabbitt** [10gen-labs/mongo-connector#203]
Official documentation says, we can have a mapping for string type for each index, named after the MongoDB database and collection names as animals.kitten.

I tried to create mapping as:

$ curl -XPUT 'http://localhost:9200/animals.kitten/_mapping' -d '
{
    "animals.kitten" : {
        "properties" : {
            "name" : {"type" : "string", "store" : true }
        }
    }
}'
But it throws the error as:

{
   "error": "ActionRequestValidationException[Validation Failed: 1: mapping type is missing;]",
   "status": 500
}
I dont know where I am wrong. I tried different alternatives which did not worked as well. Even though elasticsearch generate dynamic mapping for each field in index animals.kitten (i.e. GET localhost:9200/animals.kitten/_mapping is working fine), it would be great if I could manually insert the mapping or update it later.

**Comment by lovett89** [comment]
@BlackRabbitt 
I think you may be missing the mapping type from the URI to which you're sending the PUT request. The following works for me:

    curl -XPUT http://localhost:9200/animals.kitten/_mapping/string -d'{
        "string": {
          "properties": {
            "name": {
              "type": "string",
              "stored": true
            }
          }
        }
    }'

Then we can add documents to the `kitten` collection in the `animals` database in MongoDB, and this mapping will apply to those documents sent to Elasticsearch from Mongo Connector. See the [PUT Mapping API](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-put-mapping.html) for Elasticsearch.

**Comment by BlackRabbitt** [comment]
@lovett89 
As you suggest, I updated the mapping as below:
PUT http://localhost:9200/animals.kitten/_mapping/string
{
    "string": {
      "properties": {
        "name": {
          "type": "string",
          "stored": true
        }
      }
    }
}

And I tried to insert name in mongodb as follow:
>use animals
>db.kitten.insert({name:2})
(insert successfull)

Then, I searched for mapping as: GET animals.kitten/_mapping
The mapping was not what I was expecting. The response is:
{
   "animals.kitten": {
      "mappings": {
         "string": {
            "properties": {
               "name": {
                  "type": "double"
               }
            }
         }
      }
   }
}

Am I wrong anywhere? I think mongo-connector should think twice on indexing data to elasticsearch.

**Comment by lovett89** [comment]
The "type" of "name" changed because a document with `{"name": 2.0}` was inserted, and the "string" type, as currently set up, has a [dynamic mapping](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-dynamic-mapping.html). This is just a property of dynamic mappings in Elasticsearch. Besides, Mongo Connector doesn't use the Elasticsearch mappings to enforce a schema on MongoDB documents (see https://github.com/10gen-labs/mongo-connector/issues/140). For that, check out the `--fields` option.

I'd suggest reading Elasticsearch's [documentation on mappings](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping.html) to see what advantages mappings provide and how to set them up. Mongo Connector doesn't attempt to set up mappings for you, it merely moves documents from MongoDB to Elasticsearch, and Elasticsearch either creates a dynamic mapping automatically, or uses the one already set up at `/<database.collection>/string`.

**Comment by BlackRabbitt** [comment]
Thank you. Now my question has been answered. And sure, I will follow your suggestion. Thanks again.
