### ISSUE TITLE
How can I exclude fields when indexing...

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#222]
Hi,

I can index certain fields by using -i, but how can I exclude fields in case I just want to leave out one or two fields when porting data from Mongo and indexing on an initial port?

What would happen after all the fields are indexed when I update the Elasticsearch mapping?
What would happen if a document got indexed with a field that's not been mapped after the mapping document has been created in Elasticsearch?

Just some questions I had while I prepare our architecture.

Thanks,
Ben.

**Comment by llvtt** [comment]
**Q.** How can I exclude fields?
**A.** There is no option for excluding fields right now, but I'll make a feature request for it.

**Q.** How does updating a mapping affect already indexed documents?
**A.** When a mapping is updated in Elasticsearch, it applies only to future documents that are indexed. Documents that were already indexed with the old mapping need to be re-indexed for the changes to take effect on them.

**Q.** What happens if a document contains a field not in the Elasticsearch mapping that I created manually?
**A.** As long as the `dynamic` property of the mapping is not set to `strict`, then Elasticsearch will make its best guess as to what type the field is. See http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-dynamic-mapping.html#mapping-dynamic-mapping

**Comment by llvtt** [comment]
I'm closing this issue since it hasn't been active in awhile. Please feel free to reopen this if there's more to discuss.
