### ISSUE TITLE
Mongo-connector crashes due to Elasticsearch mapping required...what happens when mongo connector restarts?

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#229]
Hi,

I'm doing a very large import of my data and I'm building my Elasticsearch mapping as I progress, meaning I start the mongo connector and let it fail every time a mapping is required, then insert the mapping on Elasticsearch and try again. However, I delete the mongo connector log and the oplog.timestamp file every time and start over, if I were to just delete the log, but keep the oplog.timestamp file, would mongo connector be able to retry the record it failed now that it has the mapping or would it completely bypass the mapping and start from the next document, or where would it start?

Thanks,
Ben.

**Comment by llvtt** [comment]
@bdesilva

Mongo Connector usually only logs Exceptions if it encounters them while processing the oplog. When this happens, the checkpoint continues to be updated regardless of these logged Exceptions. This means that if you restart `mongo-connector` without deleting the `oplog.timestamp` file, `mongo-connector` will resume processing the oplog at the same point at which it was stopped, after the problematic documents that it already failed to process.

If `mongo-connector` were to exit for some reason due to a fatal Exception while processing an oplog record, then the checkpoint is not updated; `mongo-connector` just logs the Exception, re-raises it, then exits. If you restart `mongo-connector` after this has happened, it will attempt to re-process that record.

Keep in mind that the `oplog.timestamp` file is used only for keeping track of where Mongo Connector is with regard to the oplog. While doing a "collection dump" (just importing data for the first time), the oplog isn't used at all, so all Exceptions during this phase cause `mongo-connector` to exit (unless you've set `--continue-on-error`), and restarting `mongo-connector` will start the collection dump from the beginning.

**Comment by bdesilva** [comment]
@llvtt Thanks so much, that helps! If I've set the --continue-on-error tag, then any exceptions is comes across for those documents Elasticsearch is unable to index, such as mapping issues, will it skip all those records and continue with the next documents that it can index?

**Comment by llvtt** [comment]
Yes. Note that `--continue-on-error` only applies to the collection dump.

**Comment by bdesilva** [comment]
Sounds good! Thanks.

**Comment by llvtt** [comment]
This discussion seems complete, so I'll close this issue. Feel free to reopen if you think there's more to discuss.
