### ISSUE TITLE
Elasticsearch indexes for a few hours, then drops to zero, then starts up again...

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#232]
Hi,

I've noticed at times that during a mongo connector import, Elasticsearch drops it's indexing from about 90-100 documents per second to zero documents per second and then starts up the indexing process later again (sometimes an hour or two, sometimes not at all). There are no errors in the logs and I've optimized Elasticsearch to handle a large data port by not using replica shards and turnong off the index refresh interval.

Any ideas to why this might be?

Thanks,
Ben.

**Comment by llvtt** [comment]
It's hard to say if this issue is on the mongo-connector side or the Elasticsearch side, and it is beyond the scope of a Mongo Connector Github issue. You might have more success posting the the [mongodb-user](https://groups.google.com/forum/#!forum/mongodb-user) group or at [Elasticsearch](https://groups.google.com/forum/#!forum/elasticsearch).

If you find that this is a performance problem or bug in Mongo Connector, then please open another issue here.
