### ISSUE TITLE
Verbosity of log file

### ISSUE THREAD

**Issue by heichwald** [10gen-labs/mongo-connector#234]
Is there a way not to output the full json of the document to the log file? I tried --verbose 0 and --verbose 1 but they seem to do the same here.
When I run the initial dump to Elastic, I get 10GB for the log file in matter of minutes, I wonder if it is possible?
I think it was in version 1.3

Thanks

**Comment by llvtt** [comment]
The problem is that there's only two effective log levels for mongo-connector: non-verbose (INFO-level) and debug (DEBUG-level). The INFO level (non-verbose) is actually pretty chatty, so it'd be nice to move some of the INFO-level logging to DEBUG. I'll make a patch for this later today.

It's worth noting that mongo-connector can rotate its own log files, so you could rotate the logs every few hours/minutes if you so chose to save space. Check out [logging options](https://github.com/10gen-labs/mongo-connector/wiki/Configuration%20Options#configure-logging).

**Comment by joe-mojo** [comment]
Sorry but this is a bug as doc states that 0 is ERROR, 1 is WARNING, 2 is INFO and 3 is DEBUG. But setting any nulber set verbosity to DEBUG, which is not expected.

**Comment by llvtt** [comment]
@joe-mojo The different verbosity levels only apply to Mongo Connector >= 2.0.3. Before this, any nonzero setting for verbosity was DEBUG-level. What version are you using?

**Comment by joe-mojo** [comment]
2.0.2
Didn't see 2.0.3 coming since I installed mongo-connector last week...
