### ISSUE TITLE
Clean NaN when sending documents to ElasticSearch

### ISSUE THREAD

**Issue by jaredkipe** [10gen-labs/mongo-connector#238]
ElasticSearch fails to parse documents if there are non-standard tokens like 'NaN', 'Infinity' and '-Infinity' in the document body.

There is a index setting 'index.mapping.ignore_malformed' that may help to avoid the field, but it does not seem to help in this case.  (probably because the JSON itself won't parse, and never makes it to field validation)

**Comment by jaredkipe** [comment]
I haven't made a pull request, but I did solve my problems by modifying mongo_connector/doc_managers/formatters.py
(python is NOT a language I've programmed in before)


>+import math
>+import sys
>
>... ~line 90
>        elif isinstance(value, (int, long, float)):
>+            if math.isnan(value):
>+                value = 0.0
>+            elif math.isinf(value):
>+                value = sys.maxint
>            return value

**Comment by jaredkipe** [comment]
If this is idiomatic and not a problem (i.e. should elasticsearch get its own formatter?), I can create a pull request.

**Comment by llvtt** [comment]
@jaredkipe 
A pull request would be welcome. One thing that concerns me, though, is replacing NaN and infinity with another valid int/long/float value, since then we won't know that the value was originally NaN/inf and not sys.maxint or 0. Perhaps we could also add a field to the document at this point called "nan_fields" that contains the names of the fields that had their values replaced from NaN to something else, similar to http://logstash.net/docs/1.4.2/inputs/collectd. We can do the same thing with infinity and "inf_fields". Alternatively, we could just drop the offending fields from the document.

**Comment by jaredkipe** [comment]
@llvtt 
It concerns me as well, but whenever you are replicating data, compromises are bound to happen.

I haven't tried to reproduce it, but the real 'problem' with the current implementation isn't that it errors on trying to insert the document (though that is obviously worse than just having an invalid 0 in a field).  But it actually crashed mongo-connector when something changed in the document and it went to update the non-existent document.
In this case, having an inaccurate document is better than no document at all.

I agree that removing the field in entirety is also a good way to go compared to sentinel fields like maxint.

**Comment by llvtt** [comment]
Sounds good to me. Would you like to make a pull request for removing fields with invalid values?

**Comment by jaredkipe** [comment]
Works for me, thanks!

**Comment by llvtt** [comment]
resolved by pull request merged in 0454fad9afbc3e8e4560930efb064eed6bacbefe
