### ISSUE TITLE
Mapping getting overridden

### ISSUE THREAD

**Issue by hirenhcm** [10gen-labs/mongo-connector#259]
Hi,
Am using sailsjs, mongo, elasticsearch and mongo-connector. mongo-connector is use to sync elasticsearch from mongodb.

Issue is when ever I start my sails server with mongo-connector running all the custom mapping(geo_point) are remove and re-created by mongo-connector. In elasticsearch i have also tried to create a mapping config file but that is also not respected.

Is there a way to tell the connector not to override my mapping. I have also tried to create my mapping before starting mongo-connector. But it all get recreated to default mapping where my geo_point mapping is lost.

I use the following command to start mongo-connector
```
mongo-connector -m localhost:27017 -t localhost:9200 -d elastic_doc_manager
```

These are the logs i see in elasticsearch console when my sailsjs server has started. This is shown for all the models.
```
[2015-05-25 00:19:01,822][INFO ][cluster.metadata         ] [Thumbelina] [[myindex]] remove_mapping [[location]]
[2015-05-25 00:19:01,859][INFO ][cluster.metadata         ] [Thumbelina] [myindex] create_mapping [location]
[2015-05-25 00:19:01,962][INFO ][cluster.metadata         ] [Thumbelina] [myindex] update_mapping [location] (dynamic)
```
Please suggest me if i am missing something.

**Comment by llvtt** [comment]
@hirenhcm 
Can you please provide verbose logs from `mongo-connector` from when this happened? Thanks.

**Comment by hirenhcm** [comment]
@llvtt 
Thanks for you response

But I was able to solve my issue by modifying the doc_manager python script.

**Comment by llvtt** [comment]
@hirenhcm Do you mind sharing what modifications you made? I'd like to understand/fix this before the next release.

**Comment by hirenhcm** [comment]
@llvtt 
As of now the for a quick fix/workaround i have commented the code in elastic_doc_manager.py where it deletes/remove the mapping.
```
91            for _db in dbs:
92                self.elastic.indices.delete(index=_db.lower())
```

What I was planning in future, was to write a logic to check if a mapping already exists, which would have been  configured/create via template, mapping config, or via dynamic config etc. But as of now commenting the above works for me. 

What are your suggestions? Do you see any potholes that i have to take care of with this workaround?

**Comment by llvtt** [comment]
@hirenhcm 
That's a fine workaround. That code should only be called, though, when you drop a MongoDB database. Here, perhaps instead of deleting the index, Mongo Connector should instead remove all documents from the index (and thereby preserving any mapping/index configuration). Does this sound like a saner action to take for `dropDatabase`?

**Comment by hirenhcm** [comment]
Yes this sounds correct. It would be more logical to just truncate type/document data keeping the mapping and settings.

**Comment by Tokenyet** [comment]
I just found out that delete setting/mapping is still a default behavior right? I'm using intergration testing with mocha, but got this issue. I must drop collections a multiple times, so this behavior seems bad to lose mapping and settings in my case.

--

Edit: 
My Solution here, I used Template to match index, so that won't be deleted even If the collections dropped.
