### ISSUE TITLE
default logging should be stream and not file

### ISSUE THREAD

**Issue by dan-vine** [10gen-labs/mongo-connector#273]
in connector.py:

    default_logging = {
        'type': 'file',
        'filename': 'mongo-connector.log',
        'rotationInterval': constants.DEFAULT_LOGFILE_INTERVAL,
        'rotationBackups': constants.DEFAULT_LOGFILE_BACKUPCOUNT,
        'rotationWhen': constants.DEFAULT_LOGFILE_WHEN,
        'host': constants.DEFAULT_SYSLOG_HOST,
        'facility': constants.DEFAULT_SYSLOG_FACILITY
    }

I guess type should be stream. I couldn't found a way to set it to stream.

**Comment by llvtt** [comment]
@dan-vine All output goes to mongo-connector.log by default in the 2.0 version of mongo-connector. There wasn't a way to change it to stream log output to stdout/stderr, as was the old behavior. I just added a `--stdout` option to log all output to stdout, rather than to a log, if you want to try it out. This can also be configured by setting "logging.type" to "stream" in the config file.

**Comment by llvtt** [comment]
This is complete as of a1a827f04606be8f892de4dd829f9bd565eb6fd5 and is part of the 2.1 release.
