### ISSUE TITLE
Solr mutliValued fields and reformatting documents before insertion into Solr

### ISSUE THREAD

**Issue by evalapply** [10gen-labs/mongo-connector#276]
Hello,
I'm confused about how the documents reformatting in solr_doc_manager (_clean_doc) is supposed to work with multiValued fields in Solr.
I was using a very out of date version of mongo-connector until recently and documents containing lists were syncing nicely with:
```
<field name="category">value1</field>
<field name="category">value2</field>
...
```
but after mongo-connector upgrade the documents are reformatted to:
```
<field name="category.0">value1</field>
<field name="category.1">value2</field>
...
```
and these fields are not synced anymore.

**Comment by llvtt** [comment]
See https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20Solr#nb-key-names-and-document-flattening for details on how document flattening works in Solr.

**Comment by evalapply** [comment]
Hi,Thanks for a quick reply. I actually read the wiki page before, but it's still unclear to me how multiValued fields fit in. My current solution is commenting out the _clean_doc method, which makes my setup work as before (in my case changing schema.xml would affect many applications using the core). Perhaps I should ask this way: is it true that mongo documents containing lists are currently unsyncable with multiValued="true" fields in Solr? I know _clean_doc method is always called, but maybe I'm missing something e.g. in my Solr config?

**Comment by llvtt** [comment]
Given the current method of flattening, no two fields within a document
will have the same name, so there won't be any multiValued fields emitted
from mongo-connector. Rationale behind the flattening scheme is discussed
here:
https://github.com/10gen-labs/mongo-connector/issues/148#issuecomment-48931974.
Commenting-out the _clean_doc method should be fine if:

1. All the fields within each document are defined in your schema (so Solr
doesn't fail to index a document due to an unrecognized field)
2. Each document is already flat (i.e there are no sub-documents)

**Comment by evalapply** [comment]
Thank you very much!
