### ISSUE TITLE
OperationFailed: [Reason: version conflict for 36302267 expected=1 actual=-1]

### ISSUE THREAD

**Issue by JyunTang** [10gen-labs/mongo-connector#281]
Hi,

I have setup Solr-Mongo Integration on ubuntu. The following is my environment

Solr 5.1.0
Mongo 3.0.3
Mongo Connector 2.1

this the mongo-connector parameters I am using 
`sudo mongo-connector -m localhost:27017 -t http://localhost:8983/solr/demo -d solr_doc_manager`

 

[CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 288, in bulk_upsert
    self.solr.add(batch, **add_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pysolr.py", line 813, in add
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/usr/local/lib/python2.7/dist-packages/pysolr.py", line 399, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/local/lib/python2.7/dist-packages/pysolr.py", line 331, in _send_request
    raise SolrError(error_message)
OperationFailed: [Reason: version conflict for 36302267 expected=1 actual=-1]
015-07-13 23:48:22,709 [ERROR] mongo_connector.oplog_manager:551 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient('localhost', 27017), u'local'), u'oplog.rs')
2015-07-13 23:48:23,085 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140119189448448)> unexpectedly stopped! Shutting down

what is this error mean and how to config?thanks

**Comment by llvtt** [comment]
This means that there is a version conflict with one of the documents that mongo-connector is trying to insert into Solr (usually because the `_version_` field in a document doesn't match the the `_version_` of that document already in Solr). The strange thing about this is that this is happening during the initial import phase, so mongo-connector shouldn't be specifying a version for any documents. Do your documents include a `_version_` field coming out of MongoDB?

This page looks like it has a decent explanation of update/versioning sematics in Solr: https://wiki.apache.org/solr/Per%20Steffensen/Update%20semantics.

What does your `updateHandler` configuration look like in `solrconfig.xml`?

**Comment by JyunTang** [comment]
`<updateHandler class="solr.DirectUpdateHandler2">`

    
    <updateLog>
      <str name="dir">${solr.ulog.dir:}</str>
    </updateLog>

    
    <autoCommit>
      <maxTime>15000</maxTime>
      <openSearcher>false</openSearcher>
    </autoCommit>

    
    
     
    
    
    
 ` </updateHandler>`

**Comment by llvtt** [comment]
I'm not sure what the default `semanticsMode` is for Solr 5, but you could try specifying one explicitly to adjust document versioning rules, e.g.:

    <semanticsMode>classic-consistency-hybrid</semanticsMode>

inside your `updateHandler` definition. See the explanation for different `semanticsMode`s under the "Solution" heading near the top of this page: https://wiki.apache.org/solr/Per%20Steffensen/Update%20semantics.

**Comment by JyunTang** [comment]
yes,there is a `_version_` field in my documents

**Comment by llvtt** [comment]
That's probably what's causing the problem, since `_version_` has a special significance in Solr. You can either:

- specify the fields you want to copy from each document (excluding `_version_`) using the [fields](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#fields) option
- turn off document versioning by setting the `semanticsMode` to `classic`.

**Comment by JyunTang** [comment]
Thank you very much!
