### ISSUE TITLE
Question:   Running multiple mongo connector (different addresses) with same ES namespace

### ISSUE THREAD

**Issue by sukrit007** [10gen-labs/mongo-connector#293]
The wiki  currently mentions that we should operate on mutually exclusive namespaces
https://github.com/10gen-labs/mongo-connector/wiki/FAQ#can-i-run-more-than-one-instance-of-mongo-connector-at-the-same-time

I have 2 mongo clusters using similar namespaces  and want to get data to a common elastic search.  Is there any issue running this : 

```
mongo-connector -m address1  -n a.b -g A.B
mongo-connector  -m address2 -n a.b -g A.B
```

**Comment by llvtt** [comment]
There should be no problem doing that.

**Comment by sukrit007** [comment]
thanks.

**Comment by 42matters** [comment]
What about:

mongo-connector -n a.b -g M.N
mongo-connector -n a.c -g X.Y

**Comment by ShaneHarvey** [comment]
@42matters there should also be no problem with that. If `a.b` and `a.c` are in the same replica set, there's no need to run two mongo-connector instances. Instead run:

`$ mongo-connector -m replsetaddress -n a.b,a.c -g M.N,X.Y -t elasticaddress ...`

Otherwise, you need to run two connectors like you said.
